version: '3.8'

networks:
  external:                     
    driver: bridge             

services:
  # PostgreSQL Service
  postgres:
    image: postgres:14
    container_name: postgres_db
    ports:
      - "5432:5432"   
    environment:
      POSTGRES_USER: ${DB_USER}          
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_DB: ${DB_NAME}            
    networks:
      - external                      
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  # Redis Service
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"                      
    networks:
      - external                          
    volumes:
      - redis_data:/data  
    command: ["redis-server", "--appendonly", "yes"]               

  # MinIO Service
  minio:
    image: minio/minio:latest
    container_name: minio_storage
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}    
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"                         
      - "9001:9001"                          
    networks:
      - external                            
    volumes:
      - minio_data:/data                      
    command: server /data --console-address ":9001"

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-docker/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-docker/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - external
    depends_on:
      - app  # غيّره حسب اسم حاوية التطبيق لديك

  # Certbot Service (Let's Encrypt)
  certbot:
    image: certbot/certbot
    container_name: certbot_ssl
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done"
    networks:
      - external

volumes:
  postgres_data:
  redis_data:
  minio_data:
